name: DreamJournal
options:
  bundleIdPrefix: com.moonbeat
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "2"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm.git
    from: "5.0.0"

targets:
  DreamJournal:
    type: application
    platform: iOS
    sources:
      - path: DreamJournal
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moonbeat.ai
        INFOPLIST_FILE: DreamJournal/Info.plist
        PRODUCT_NAME: Moonbeat AI
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        ENABLE_PREVIEWS: YES
    dependencies:
      - package: Supabase
        product: Supabase
      - package: RevenueCat
        product: RevenueCat
      - package: RevenueCat
        product: RevenueCatUI
    entitlements:
      path: DreamJournal/DreamJournal.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    info:
      path: DreamJournal/Info.plist
      properties:
        CFBundleDisplayName: Moonbeat AI
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSMicrophoneUsageDescription: "Moonbeat AI needs microphone access to record your dream descriptions."
        NSSpeechRecognitionUsageDescription: "Moonbeat AI uses speech recognition to transcribe your dream recordings."
        NSCameraUsageDescription: "Moonbeat AI may use the camera for future features."

schemes:
  "Moonbeat AI":
    build:
      targets:
        DreamJournal: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
