-- Add interpretation column to dreams table for AI-generated dream insights
-- This column stores the personalized dream interpretation generated by LLM

ALTER TABLE public.dreams
ADD COLUMN IF NOT EXISTS interpretation TEXT;

-- Add comment for documentation
COMMENT ON COLUMN public.dreams.interpretation IS 'AI-generated dream interpretation and insights (Pro feature)';
